### ISSUE TITLE
Store last scrape data locally as JSON

### ISSUE THREAD

**Issue by elwha1** [elwha1/calscrape#10]
Basic flow should be:
- Check whether JSON file from last scrape exists
- If not, run a full scrape and store
- If yes, run comparison against the JSON using hearings_diff module and output new hearings only
- Save the latest scrape as the latest file

Questions:
- Should the JSON file store the date of the latest scrape
- How to handle older scrape data? Should it be deleted/overwritten?

**Comment by elwha1** [comment]
Would a `pickle` be a better option to implement this feature?

**Comment by benghancock** [comment]
Implemented in v2.0.1
