### ISSUE TITLE
implement argparse in calscrape

### ISSUE THREAD

**Issue by elwha1** [elwha1/calscrape#6]
The modules `spatula` and `calparse` are being deprecated and removed, to be replaced by `calendar_parser`, in the next major version release. The new version should use Python's `argparse` library to allow user to input several arguments:
- desired jurisdiction (e.g. "cand")
- print all hearings (to stdout)
- print only hearings matching a keyword (to stdout)
- run silently and write all scraped court hearings to a file using `logging` (more on that in a separate issue to be filed in the future)

**Comment by anseljh** [comment]
Check out [Click](https://click.palletsprojects.com/en/7.x/)!

**Comment by elwha1** [comment]
Thanks @anseljh! I've heard of Click and it seems neat. Is the main benefit over `argparse` its explicit handling of options vs arguments? Click also seems more robust in terms of offering built-in prompts, which is nice.

**Comment by anseljh** [comment]
Yeah, it does a bunch of stuff for you like some more robust handling of files as arguments, subcommands, etc. Sort of complicated, but nice to have in your toolbox.

A much simpler option is [plac](https://micheles.github.io/plac/)!

**Comment by elwha1** [comment]
Thanks again for the suggestions @anseljh! I ended up going with `argparse` this time around because it's in the standard lib. But will check out both `click` and `plac` in the future!
